version: '3'

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.32.0.0/24
services:
    elementsd:
        container_name: 'elements'
        build:
            context: .
            args:
                release: elements-0.18.1.1
        networks:
            app_net:
                ipv4_address: 172.32.0.2
        ports:
            - "127.0.0.1:18444:18444"
            - "127.0.0.1:7040:7040"
        command: >
            elementsd 
            -chain=liquidregtest
            -debug
            -listenonion=0 
            -server=1 
            -rpcallowip=172.32.0.3
            -rpcallowip=172.32.0.2
            -rpcallowip=172.0.0.1
            -rpcbind=0.0.0.0 
            -rpcuser=elements 
            -rpcpassword=elements 
            -validatepegin=0
    electrs:
        container_name: 'electrs'
        build:
            context: ./electrs
            dockerfile: Dockerfile
        networks:
            app_net:
                ipv4_address: 172.32.0.3
        ports:
            - "127.0.0.1:3002:3002"
        tty: true
        stdin_open: true
        command: >
            /opt/electrs/target/release/electrs 
            -vvvv
            --timestamp
            --jsonrpc-import
            --network liquidregtest
            --cookie elements:elements
            --daemon-rpc-addr 172.32.0.2:7040
            --http-addr 0.0.0.0:3002
